#!/bin/bash

echo "*************************************"
echo "* Jungle Cat Software | AWS-Toolkit *"
echo "*             FirstBoot             *"
echo "*************************************"
export dateformat='%Y-%m-%d %H:%M:%S.%N UTC%z'

trap 'echo "Error on line $LINENO during FirstBoot at $(date +"${dateformat}")" >&2; exit 99' ERR

#Clean up so we don't run again next time
removeFirstBoot

#Run the pre-config. This collects the new Instance UserData and
#  uses it to collect and gather the config data, and execute it.
doPreConfig
