#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Please specify at least one package to install" >&2
	exit 1
fi

if apt-get --version &>/dev/null; then
	apt-get install --assume-yes "$@" &>/dev/null
	exit $?
elif yum --version &>/dev/null; then
	yum --assumeyes install "$@" &>/dev/null
	exit $?
else
	echo "No package mangers found" >&2
	exit 2
fi
