#!/bin/bash

if apt-get --version &>/dev/null; then
	apt-get update &>/dev/null
	exval=$?
	if [ $exval -ne 0 ]; then
		exit $exval
	fi
	apt-get upgrade --assume-yes &>/dev/null
	exit $?
fi

if yum --version &>/dev/null; then
	yum --assumeyes upgrade  &>/dev/null
	exit $?
fi
