#!/bin/bash
echo "==System Package Updater=="
if [[ "x${dateformat}" != "x" ]]; then
	echo -e "Begin at $(date +"${dateformat}")"
fi

if apt-get --version &>/dev/null; then
	echo -e "\tRunning apt-get update..."
	apt-get update &>/dev/null
	exval=$?
	if [ $exval -eq 0 ]; then
		echo -e "\tRunning apt-get upgrade..."
		apt-get upgrade --assume-yes &>/dev/null
		exval=$?
	fi
fi

if yum --version &>/dev/null; then
	echo -e "\tRunning yum upgrade..."
	yum --assumeyes upgrade  &>/dev/null
	exval=$?
fi

if [ $exval -eq 0 ]; then
	echo -e "\t[DONE]"
else
	echo -e "\t[FAIL] Code: ${exval}"
	exit $exval
fi
