#!/bin/bash

echo "*************************************"
echo "* Jungle Cat Software | AWS-Toolkit *"
echo "*           AMI Generator           *"
echo "*************************************"
export dateformat='%Y-%m-%d %H:%M:%S.%N UTC%z'

trap 'echo "Error on line $LINENO during build at $(date +"${dateformat}")" >&2; exit 99' ERR

scriptroot=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
lsbdistro=$(lsb_release -i | sed -r 's/^Distributor ID:\W*(.*)$/\L\1/')
lsbreleasename=$(lsb_release -c | sed -r 's/^Codename:\W*(.*)$/\L\1/')

# Add global scripts directory
globalscripts="${scriptroot}/global"
if [ -d "${globalscripts}" ]; then
	echo "Found global scripts: ${globalscripts}"
	PATH="${globalscripts}:${PATH}"
fi

# Add distro-specific scripts directory
distroscripts="${scriptroot}/${lsbdistro}/all"
if [ -d "${distroscripts}" ]; then
	echo "Found distro-specific scripts: ${distroscripts}"
	PATH="${distroscripts}:${PATH}"
fi

# Add release-specific scripts directory
releasescripts="${scriptroot}/${lsbdistro}/${lsbreleasename}"
if [ -d "${releasescripts}" ]; then
	echo "Found release-specific scripts: ${releasescripts}"
	PATH="${releasescripts}:${PATH}"
fi

export PATH

echo -e "\nStarting at $(date +"${dateformat}")"
export image_id_path="/tmp/ImageId"

upgradeSystemPackages
installSystemPackages python3 python3-pip puppet cloud-utils
installPythonPackages awscli
installFirstBoot

createAMI

echo -e "\nFinished at $(date +"${dateformat}")"

shutdownAfterAMIComplete
